# Generated by Django 3.2.5 on 2021-07-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0001_initial'),
        ('app_employee', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cities_for_work',
            field=models.ManyToManyField(related_name='employees_for_work', to='app_option.City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app_option.city'),
        ),
        migrations.AddField(
            model_name='employee',
            name='min_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app_option.minsalary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='techs_for_work',
            field=models.ManyToManyField(related_name='employees', to='app_option.Technology'),
        ),
    ]
