# Generated by Django 3.2.5 on 2021-07-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0002_auto_20210717_2333'),
        ('app_employee', '0004_auto_20210717_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cities_for_work',
            field=models.ManyToManyField(blank=True, related_name='employees_for_work', to='app_option.City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='techs_for_work',
            field=models.ManyToManyField(blank=True, related_name='employees', to='app_option.Technology'),
        ),
    ]
