# Generated by Django 3.2.5 on 2021-07-13 08:01

import app_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[app_account.models.phone_validate])),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('is_employer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
