# Generated by Django 3.2.5 on 2021-07-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='name',
            new_name='title',
        ),
    ]
