# Generated by Django 3.2.5 on 2021-07-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_option', '0002_auto_20210717_2333'),
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_status', models.CharField(choices=[('E', 'end'), ('PE', 'permanent exemption'), ('EE', 'education exemption'), ('S', 'serving'), ('N', 'not matter')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('min_experience', models.CharField(choices=[('L3', 'less than 3 year'), ('3T6', 'between 3 and 6 year'), ('G6', 'greater than 6 year'), ('N', 'not matter')], max_length=100)),
                ('job_type', models.CharField(choices=[('F', 'full time'), ('P', 'part time'), ('I', 'internship'), ('R', 'remote'), ('A', 'all')], max_length=100)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N', 'not matter')], max_length=100)),
                ('min_degree', models.CharField(choices=[('S', 'student'), ('Di', 'diploma'), ('B\u200cٰٰٰ\u200c', 'bachelor'), ('M', 'masters'), ('Do', 'doctorate')], max_length=100)),
                ('description', models.TextField()),
                ('register_date', models.DateTimeField()),
                ('is_expire', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app_option.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app_option.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app_company.company')),
                ('min_salary', models.ForeignKey(blank=True, help_text='blank for agreement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app_option.minsalary')),
                ('techs', models.ManyToManyField(related_name='jobs', to='app_option.Technology')),
            ],
        ),
    ]
