# Generated by Django 3.2.5 on 2021-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
