# Generated by Django 3.2.5 on 2021-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0002_auto_20210717_2333'),
        ('app_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='techs',
        ),
        migrations.AddField(
            model_name='job',
            name='techs',
            field=models.ManyToManyField(related_name='jobs', to='app_option.Technology'),
        ),
    ]
