# Generated by Django 3.2.5 on 2021-07-30 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_option', '0002_auto_20210717_2333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('logo', models.ImageField(default='default_company_logo.jpg', upload_to='')),
                ('web_site', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.URLField(blank=True, null=True)),
                ('number_of_employees', models.CharField(blank=True, choices=[('1T10', '1 to 10'), ('10T50', '10 to 50'), ('50T100', '50 to 100'), ('100T250', '100 to 250'), ('250T1000', '250 to 1000'), ('+1000', 'more than thousand')], max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='app_option.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='app_option.city')),
                ('technologies', models.ManyToManyField(blank=True, related_name='companies', to='app_option.Technology')),
                ('user', models.OneToOneField(limit_choices_to={'is_active': True, 'is_company': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
