# Generated by Django 3.2.5 on 2021-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
