# Generated by Django 3.2.5 on 2021-07-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0001_initial'),
        ('app_company', '0003_auto_20210715_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='app_option.city'),
        ),
        migrations.AddField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(related_name='companies', to='app_option.Technology'),
        ),
    ]
