# Generated by Django 3.2.5 on 2021-07-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_company', '0004_auto_20210717_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='app_option.Technology'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_active': True, 'is_company': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
