# Generated by Django 3.2.5 on 2021-07-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0002_auto_20210717_2333'),
        ('app_company', '0005_auto_20210717_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='app_option.category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='companies', to='app_option.Technology'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
