# Generated by Django 3.2.5 on 2021-07-31 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_job', '0002_auto_20210731_1058'),
        ('app_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('CFI', 'confirmation for interview'), ('F', 'failed'), ('H', 'hired'), ('S', 'see'), ('N', 'not see')], default='N', max_length=100)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applys', to='app_employee.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applys', to='app_job.job')),
            ],
        ),
    ]
