# Generated by Django 3.2.5 on 2021-07-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0002_auto_20210731_1058'),
        ('app_employee', '0001_initial'),
        ('app_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('job', 'employee')},
        ),
    ]
